server:
  port: 8000
spring:
  application:
    name: chatpot
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    vertex:
      ai:
        gemini:
          project-id: ${GEMINI_PROJECT_ID}
          location: asia-northeast3
chat:
  system:
    message: ${CHAT_SYSTEM_MESSAGE}
